### PR TITLE
Added an helper script to be used with pam_mount

### PR DESCRIPTION
**Pull request by aacebedo**
As we discussed in #20 .
Feel free to integrate it :)
I modified the PKGBUILD and cargo file to install the script but I am not sure of the path.
Can you check it before merging ?

### CODE REVIEW

**Comment by aacebedo** [comment]
Hi there
Can you give a look to this PR please ? I would like to update my machine initialization scripts and having the helper is needed :)

**Comment by shimunn** [comment]
Sorry, for the long wait, a couple points for improvement:

- you seem to have removed the bash completions from the .deb
- your script requires a PIN to be used, which should be optional
- I'd be nice to have this in a separate folder like pam_mount

**Comment by aacebedo** [comment]
My bad, I deleted the line for the completion.
I added a check for the pincode and moved to the pam_mount folder.

I think there is a problem with the PKGBUILD especially for the path to the script but I do not know how to use it.
Can you take a look ?

**Comment by shimunn** [comment]
Should be 

`    install -Dm 755 ../pam_mount/fido2luksmounthelper.sh -t "${pkgdir}/usr/bin"`

**Comment by aacebedo** [comment]
Hi
I think I fixed every remarks :)

**Comment by shimunn** [comment]
forgot to push?

**Comment by aacebedo** [comment]
Hum I think everything has been pushed in the PR

**Comment by shimunn** [comment]
> I think there is a problem with the PKGBUILD especially for the path to the script but I do not know how to use it.
Can you take a look ?


> Should be

> install -Dm 755 ../pam_mount/fido2luksmounthelper.sh -t "${pkgdir}/usr/bin"

**Comment by aacebedo** [comment]
Hum sorry again. Shall be fixed now.

**Comment by shimunn** [comment]
No problem :)

**Pull request merged**
